### ISSUE TITLE
Padding for Window Buttons

### ISSUE THREAD

**Issue by sxzz** [elk-zone/elk-native#16]
We should add some padding for macOS (macOS only I guess) for window controlling buttons.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/6481596/212317298-87b83b7a-3566-4520-926a-8bf2ebbccbd0.png">

**Comment by Moshyfawn** [comment]
There's a lot to this issue as I don't think Tauri exposes an easy way to determine the decorations / title bar safe areas for different devices.

The solution is to add a custom drag-area to the Elk web client [at the top of the default layout](https://github.com/elk-zone/elk/blob/a9427e2ea0ef94c440bd7148196cd17738c962a5/layouts/default.vue#L18) with a `native:` style like
```html
<div data-tauri-drag-region native:h-8 />
```

The issue is,the title bar widget _(like OS X traffic lights)_ can have different width and height based on multiple factors like user preferences or OS version _(potentially different OS in the future)_. This is the feature request that could potentially solve it tauri-apps/tauri#6030.

Currently, the sane solution is to design the top client navigation around the OS specific widgets, IMO.

**Comment by Moshyfawn** [comment]
There's been [an update](https://tauri.app/blog/2022/11/08/tauri-1-2/#enhanced-titlebar-configuration-on-macos) to improve the title bar customization

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is [no longer maintained](https://github.com/elk-zone/elk-native/pull/96/), much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
