### ISSUE TITLE
Windows Defender Smart Screen blocking Elk Native v0.2.0

### ISSUE THREAD

**Issue by piotrski** [elk-zone/elk-native#45]
> @SharonGibson3@newsie.social
[@elk](https://newsie.social/@elk@webtoo.ls) Windows Defender Smart Screen won't let me open Elk Native v0.2.0
Is there a way to override this?

https://newsie.social/@SharonGibson3/109719852882123792

It seams to be related to code signing

**Comment by JonasKruckenberg** [comment]
For context: https://discord.com/channels/1044887051155292200/1050490177304408074/1065920823946395711

There are 2 types of code-signing certificates on Windows: Standard and Extended Validation Certificates.
Standard Certificates are interesting because they cost about 200ish€ per year **but don't actually get rid of all warnings** it's ridiculous.
Extended Validation (EV) Certificates are ridiculous for a different reason. They immediately get rid of all warnings, **but** cost about 400€ per year and in most cases come on a physical device that needs to be plugged in when signing software. I.e. incredibly impractical.

As mentioned on discord, as an avid OSS lover this is incredibly infuriating to me, I could go on long rants about this that I couldn't then legally publish publicly. Suffice it to say, I think buying any of these certificates for an OSS project that doesn't have a way to generate profit sets a dangerous precedence and only encourages this behavior demonstrated by Microsoft and certificate vendors.

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is [no longer maintained](https://github.com/elk-zone/elk-native/pull/96/), much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
