### ISSUE TITLE
Ubuntu : conflict between 2 different packages with the same name : Elk

### ISSUE THREAD

**Issue by jeanvoguet** [elk-zone/elk-native#61]
On Ubuntu, installing Elk_0.3.0_linux_x86_64.deb 

There is a big problem with the other existing package 
elk_3.99.8-4.2build1

As soon as the desktop app of Elk 0.3 is installed, it is deleted a few minutes later by an update of the other elk_3.99.8-4.2build1
It is therefore impossible to use the app.

It seems necessary to change the name so that there is no confusion between the 2 packages. 

another thing:
still on Ubuntu, no links in the Appimage work ?...

**Comment by JonasKruckenberg** [comment]
I see. I don't necessarily know what to do here, we could rename the app to something like `ElkNative` at the cost of potentially causing issues with other OS'es. I don't know if it's worth pursuing for an issue that only arises with certain setups and only with tthe .deb package (doesn't interfere with AppImages right?) Especially since .dep packages should be considered legacy packaging formats anyway.

Another option might be renaming the .dep package before uploading, though I don't know if that would change anything.

Also, please don't harass open source maintainers like this, we all do this in our spare time for fun. If you want something changed, your best chance is doing it yourselves and then submitting a pull request. Behavior like this will just get you blocked.

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is [no longer maintained](https://github.com/elk-zone/elk-native/pull/96/), much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
